config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'zip_codes#index'

  get '/zip_codes(/:zip_code)', to: 'zip_codes#show', as: 'zip_code'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/zip_code.rb
# frozen_string_literal: true

class ZipCode < ApplicationRecord
  validates :cep, :address, :district, :state, :city, :ddd, :search_count, presence: true
  validates :cep, uniqueness: true

  UFS = %w[
    AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO
  ].freeze

  def self.top_searched(limit = 3)
    order(search_count: :desc).limit(limit)
  end

  def self.top_searched_by_state
    UFS.map do |state|
      [state, where(state:).order(search_count: :desc).first]
    end
  end

  def self.count_by_state
    counts = Hash.new(0)
    all.find_each { |zipcode| counts[zipcode.state] += 1 }
    counts
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/zip_codes_controller.rb
# frozen_string_literal: true

class ZipCodesController < ApplicationController
  def show
    @zip_code = FindZipCodeService.new(zip_code: params[:zip_code]).call

    redirect_to root_path(zip_code_result: @zip_code)
  end

  def index
    @zip_code_result = params[:zip_code_result]
    @top_searched_zip_codes = ZipCode.top_searched
    @top_searched_zip_codes_by_state = ZipCode.top_searched_by_state
    @amount_zip_codes_by_state = ZipCode.count_by_state
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZipCodeFinder</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body>
    <main class="h-full">
      <%= yield %>
    </main>
  </body>
</html>

app/views/zip_codes/_amount_zip_codes_by_state.html.erb
<div class="mt-4 rounded-md border border-gray-600 shadow-sm w-1/2">
  <h2 class="text-center text-medium font-semibold leading-relaxed tracking-tight">Quantidade de CEPs por estado</h2>
  <ul class="text-center text-sm font-medium">
    <% ZipCode::UFS.each do |state| %>
      <li class="flex justify-between items-center py-2 px-20">
        <span class="w-12"><%= state %></span>
        <span><%= @amount_zip_codes_by_state[state] || 0 %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/zip_codes/_zip_code_details.html.erb
<div class="mt-4">
  <ul class="text-center text-sm font-medium">
    <li><%= zip_code_result['cep'] %></li>
    <li><%= zip_code_result['address'] %></li>
    <li><%= zip_code_result['district'] %></li>
    <li><%= zip_code_result['state'] %></li>
    <li><%= zip_code_result['city'] %></li>
    <li>DDD <%= zip_code_result['ddd'] %></li>
  </ul>
</div>

app/views/zip_codes/_zip_code_error.html.erb
<div class="mt-4 text-center text-red-600">
  <p><%= zip_code_result['error_message'] %></p>
</div>

app/views/zip_codes/_zip_code_top_searched.html.erb
<div class="mt-4 rounded-md border border-gray-600 shadow-sm w-1/2">
  <h2 class="text-center text-medium font-semibold leading-relaxed tracking-tight">CEPs mais buscados</h2>
  <ul class="text-center text-sm font-medium">
    <% 3.times do |index| %>
      <li><%= @top_searched_zip_codes[index]&.cep || '--' %></li>
    <% end %>
  </ul>
</div>

app/views/zip_codes/_zip_code_top_searched_by_state.html.erb
<div class="mt-4 rounded-md border border-gray-600 shadow-sm w-1/2">
  <h2 class="text-center text-medium font-semibold leading-relaxed tracking-tight">Mais buscados por estado</h2>
  <ul class="text-center text-sm font-medium">
    <% @top_searched_zip_codes_by_state.each do |state, zip_code| %>
      <li class="flex justify-between items-center py-2 px-20">
        <span><%= state %></span>
        <span><%= zip_code&.cep || '--' %></span>
      </li>
    <% end %>
  </ul>
</div>

app/views/zip_codes/index.html.erb
<div class="flex justify-center items-center min-h-screen">
  <div class="container mx-auto my-6 md:my-12 p-6 md:p-12 rounded shadow-lg w-full max-w-2xl">
    <h1 class="text-center text-2xl font-bold tracking-tight">ZipCode Finder</h1>
    <%= form_tag zip_code_path, method: :get do %>
      <div class="flex justify-center mt-4">
        <%= text_field_tag :zip_code, nil, class: 'block rounded-md border-1 py-1.5 shadow-sm' %>
      </div>
      <div class="text-center mt-4">
        <%= submit_tag 'Buscar', class: 'px-4 py-2 bg-blue-600 rounded-md text-white shadow-sm hover:bg-blue-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600' %>
      </div>
    <% end %>

    <% if @zip_code_result.present? %>
      <% if @zip_code_result['error_message'] %>
        <%= render 'zip_code_error', zip_code_result: @zip_code_result %>
      <% else %>
        <%= render 'zip_code_details', zip_code_result: @zip_code_result %>
      <% end %>
    <% end %>

    <div class="flex justify-center space-x-4">
      <%= render 'zip_code_top_searched' %>
    </div>

    <div class="flex justify-center space-x-4">
      <%= render 'zip_code_top_searched_by_state' %>
      <%= render 'amount_zip_codes_by_state' %>
    </div>
  </div>
</div>